01_CitiesWebsite_begin/CitiesWebsite/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CitiesWebsite.Models
{
    public class City
    {
        public string Country { get; }
        public string Name { get; }
        public string TimeZone { get; }
        public CityPopulation Population { get; }

        public City(string country, string cityName, string timeZone, CityPopulation population)
        {
            Country = country;
            Name = cityName;
            TimeZone = timeZone;
            Population = population;
        }
    }
}

01_CitiesWebsite_begin/CitiesWebsite/Models/CityPopulation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CitiesWebsite.Models
{
    public class CityPopulation
    {
        public int Year { get; }
        public int City { get; }
        public int Urban { get; }
        public int Metro { get; }

        public CityPopulation(int year, int city, int urban, int metro)
        {
            Year = year;
            City = city;
            Urban = urban;
            Metro = metro;
        }
    }
}

01_CitiesWebsite_begin/CitiesWebsite/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CitiesWebsite.Services;

namespace CitiesWebsite.Controllers
{
    public class CityController : Controller
    {
        private ICityProvider _cities;
        public CityController(ICityProvider cities)
        {
            _cities = cities;
        }

        public IActionResult ShowCities()
        {
            ViewBag.Cities = _cities;
            return View();
        }

        public IActionResult ShowDataForCity(string cityName)
        {
            ViewBag.City = _cities[cityName];
            return View();
        }

        public IActionResult GetImage(string cityName)
        {
            return File($@"images\{cityName}.jpg", "image/jpeg");
        }
    }
}

01_CitiesWebsite_begin/CitiesWebsite/ViewComponents/CityViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CitiesWebsite.Services;
using CitiesWebsite.Models;

namespace CitiesWebsite.ViewComponents
{
    public class CityViewComponent : ViewComponent
    {
        private ICityProvider _cities;

        public CityViewComponent(ICityProvider cities)
        {
            _cities = cities;
        }

        public async Task<IViewComponentResult>InvokeAsync(string cityName)
        {
            ViewBag.CurrentCity = await GetCity(cityName);
            return View("SelectCity");
        }

        private Task<City> GetCity(string cityName)
        {
            return Task.FromResult<City>(_cities[cityName]);
        }
    }
}

01_CitiesWebsite_begin/CitiesWebsite/Views/City/ShowCities.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowCities</title>
    <link type="=text/css" rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <h1>Select City</h1>
    @foreach (var item in ViewBag.Cities)
    {
        @await Component.InvokeAsync("City", item.Key)
        
    }
</body>
</html>

01_CitiesWebsite_begin/CitiesWebsite/Views/City/ShowDataForCity.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowDataForCity</title>
    <link type="text/css" rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <div>
        <h2>@ViewBag.City.Name</h2>
        <p>Country: @ViewBag.City.Country</p>
        <p>TimeZone: @ViewBag.City.TimeZone</p>
        <span>
            <img src= "@Url.Action("GetImage", new { cityName = ViewBag.City.Name})" />
        </span>
        <span>
            @await Html.PartialAsync("_CityPopulation") 
        </span>    
        <a asp-action="ShowCities">Back</a>
    </div>
</body>
</html>

01_CitiesWebsite_begin/CitiesWebsite/Views/Shared/Components/City/SelectCity.cshtml
<div>
    <h2>
        <a asp-action="ShowDataForCity" asp-route-cityname=@ViewBag.CurrentCity.Name>
        @ViewBag.CurrentCity.Name (Capital of @ViewBag.CurrentCity.Country)</a>
    </h2>
    <img src="@Url.Action("GetImage", new { cityName = ViewBag.CurrentCity.Name })" />
</div>

01_CitiesWebsite_begin/CitiesWebsite/Views/Shared/_CityPopulation.cshtml
@inject CitiesWebsite.Services.ICityFormatter cityFormatter

@{CitiesWebsite.Models.CityPopulation population =
    ViewBag.City.Population;
    <h3>City Population(@population.Year)</h3>
    <p>City: @cityFormatter.GetFormattedPopulation(population.City)</p>
    <p>Metro: @cityFormatter.GetFormattedPopulation(population.Metro)</p>
}